### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hevanaa** [kimmoli/heebo#2]
This is possibly not directly a heebo issue, but I haven't noticed any other programs not working. Since a few days ago, heebo doesn't start, but exits with a Segmentation fault. I think it started after I uninstalled some Sailfish applications (just by clicking in the GUI), but not before a reboot.

[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[D] GameView::readSettings:71 - level  37
[D] GameView::readSettings:72 - map  2
[D] GameMapSet::GameMapSet:37 - Loading map:  "/usr/share/harbour-heebo/data/map2.dat"
[D] GameMapSet::loadMap:133 - Reading maps:  25 Height:  9 Width:  6
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:103 - Could not find any zN.M subdirs!
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:129 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
[D] onRunningChanged:104 - particleSystem stopped
[D] onCompleted:103 - particleSystem ready
[D] onCompleted:54 - block size is 90 x 90
[D] :319 - getParticlesMode
[D] GameMapSet::getParticlesMode:321 - getParticlesMode  1
[D] :313 - getPenaltyMode
[D] GameMapSet::getPenaltyMode:306 - getPenaltyMode  0
[D] GameMapSet::getHighScore:234 - Map:  2 Level:  7209065 , score:  0
Segmentation fault

The directory mentioned in the message is indeed missing, there is only an empty /usr/share/themes/jolla-ambient/meegotouch directory. I cannot figure out from which package files in that directory should come from.

**Comment by kimmoli** [comment]
Ok, Jolla did change the theme paths during update to 2.0.1.x, i'm not sure is that related. I don't see such warnings.

But instead of your segfault, i see following

```
[W] qt_png_warning:499 - libpng warning: iCCP: known incorrect sRGB profile
```

but game runs fine

**Comment by hevanaa** [comment]
I found the problem. In the configuration file, there was the following:

[Mapset]
level=37
map=2

Which is not possible, because there is no level 37 in map 2. When changed to map=1, it works. I have no idea how that combination came to be, but clearly it would be better to open e.g. the first level in the first map instead of Segmentation fault.

**Comment by kimmoli** [comment]
I have heard few occurences where mapset gets messed. This _shouldn't_ happen.
Thanks.
I'll add some checks around there.

**Comment by hevanaa** [comment]
Thanks for a great game!
