### ISSUE TITLE
No more moves but no reshuffle

### ISSUE THREAD

**Issue by eson57** [kimmoli/heebo#3]
Hi,
A serious bug in my favorite Sailfish game... ;)
There is no more possible moves and yet no reshuffle.

![screen_20170305_001](https://cloud.githubusercontent.com/assets/2996154/23585467/503eb420-0180-11e7-99f6-aa8db42c3cc8.png)

**Comment by kimmoli** [comment]
oh crap. you're right, it looks serious. "production stopper" 
i'll remove heebo from the store, so no one else could hit this bug. Please uninstall.

You can move heebos still, in the bottom half, so it does not detect that there is nothing you can do.
Just resuffle manually.

**Comment by eson57** [comment]
Hmm... didn't know I could reshuffle manually. How can I do that?

**Comment by kimmoli** [comment]
Shake the phone vigorously? No, you can't resuffle manually, i meant that you need to restart level.

**Comment by eson57** [comment]
Yep, that's what I did. Thanks!

**Comment by kimmoli** [comment]
Closing this as won't fix. As a workaround, restart the level.
